-- ==========================================================
-- RIVERRAN E-COMMERCE SUPABASE SQL SCHEMA SETUP
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==========================================================

-- 1. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    customer_city TEXT,
    customer_state TEXT,
    customer_address TEXT,
    customer_pincode TEXT,
    order_notes TEXT,
    products JSONB NOT NULL DEFAULT '[]'::jsonb,
    pricing JSONB NOT NULL DEFAULT '{}'::jsonb,
    grand_total NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    raw_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow anyone (guests & authenticated users) to place orders
CREATE POLICY "Allow public order insertion" 
ON public.orders FOR INSERT 
WITH CHECK (true);

-- 4. Policy: Allow users to view their own orders or public admin viewing
CREATE POLICY "Allow reading orders" 
ON public.orders FOR SELECT 
USING (true);

-- 5. Policy: Allow updating order status
CREATE POLICY "Allow updating orders" 
ON public.orders FOR UPDATE 
USING (true);

-- 6. Index for faster queries by created_at and user_id
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
